[build]
  command = "npm run build && cp public/edge-maxing.html build/"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/edge-maxing.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 