[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/edge-maxing.html"
  to = "/edge-maxing.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"